Web/_unused/WebClimbing/Controllers/DataController.cs
// <copyright file="DataController.cs">
// Copyright © 2016 All Rights Reserved
// This file is part of ClimbingCompetition.
//
//  ClimbingCompetition is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  ClimbingCompetition is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with ClimbingCompetition.  If not, see <http://www.gnu.org/licenses/>.
//
// (Этот файл — часть ClimbingCompetition.
// 
// ClimbingCompetition - свободная программа: вы можете перераспространять ее и/или
// изменять ее на условиях Стандартной общественной лицензии GNU в том виде,
// в каком она была опубликована Фондом свободного программного обеспечения;
// либо версии 3 лицензии, либо (по вашему выбору) любой более поздней
// версии.
// 
// ClimbingCompetition распространяется в надежде, что она будет полезной,
// но БЕЗО ВСЯКИХ ГАРАНТИЙ; даже без неявной гарантии ТОВАРНОГО ВИДА
// или ПРИГОДНОСТИ ДЛЯ ОПРЕДЕЛЕННЫХ ЦЕЛЕЙ. Подробнее см. в Стандартной
// общественной лицензии GNU.
// 
// Вы должны были получить копию Стандартной общественной лицензии GNU
// вместе с этой программой. Если это не так, см. <http://www.gnu.org/licenses/>.)
// </copyright>
// <author>Ivan Kaurov</author>
// <date>30.08.2016 23:51</date>

﻿using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebClimbing.Models;
using XmlApiData;
using ClimbingCompetition;
using System.Data;

namespace WebClimbing.Controllers
{
    [AllowAnonymous]
    public class DataController : Controller
    {
        ClimbingContext db = new ClimbingContext();

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                db.Dispose();
            base.Dispose(disposing);
        }

        //
        // GET: /Data/

        public ActionResult Index(long id = 0)
        {
            var comp = db.Competitions.Find(id);
            if (comp == null || comp.Lists.Count < 1)
                return RedirectToAction("Index", "Home");

            var availableStylesL = comp.Lists
                                    .Select(l => l.Style)
                                    .Distinct()
                                    .ToList()
                                    .Select(s => new
                                    {
                                        Name = s,
                                        maxP = comp.Lists
                                             .Where(l => l.Style.Equals(s, StringComparison.OrdinalIgnoreCase))
                                             .Max(l => l.LocalIid)
                                    })
                                    .OrderByDescending(l => l.maxP);
            var availableStyles = availableStylesL.Select(l => l.Name);
            String selectedStyle = availableStyles.FirstOrDefault();
            var selectListStyles = new SelectList(availableStyles, selectedStyle);
            ViewBag.Styles = selectListStyles;
            ViewBag.SelectedStyle = selectedStyle;
            return View(comp);
        }

        public ActionResult GetGroups(long id, String style, String divId)
        {
            ViewBag.DivID = divId;
            var comp = db.Competitions.Find(id);
            if (comp == null || style == null)
                return new HttpNotFoundResult();
            var availableGroups = comp.Lists
                                  .Where(l => l.Style.Equals(style, StringComparison.OrdinalIgnoreCase))
                                  .Select(l => l.Group)
                                  .Distinct()
                                  .ToList();
            availableGroups.Sort((a, b) =>
            {
                if (a == null && b == null)
                    return 0;
                if (a == null)
                    return -1;
                if (b == null)
                    return 1;
                int n = (b.AgeGroup.MinAge ?? 0).CompareTo(a.AgeGroup.MinAge ?? 0);
                if (n != 0)
                    return n;
                return (a.AgeGroup.GenderCode.CompareTo(b.AgeGroup.GenderCode));
            });
            var grpToSelect = availableGroups.Select(gr => gr != null ?
                new { Id = gr.Iid, Name = gr.AgeGroup.SecretaryName, Value = gr } :
                new { Id = (long)0, Name = "-", Value = (Comp_AgeGroupModel)null }).ToList();
            
            var fGroup = grpToSelect.FirstOrDefault();
            object selectedGroup = (fGroup == null ? null : fGroup.Id.ToString());
            var selectListGroups = new SelectList(grpToSelect, "Id", "Name", selectedGroup);

            ViewBag.Groups = selectListGroups;
            ViewBag.SelectedGroup = selectedGroup;
            ViewBag.SelectedStyle = style;
            ViewBag.Id = id;
            return PartialView();
        }

        public ActionResult GetRounds(long id, long groupId, String style, String divId)
        {
            ViewBag.DivID = divId;
            var comp = db.Competitions.Find(id);
            if (comp == null)
                return new HttpNotFoundResult();
            var availableLists = comp.Lists
                                 .Where(l => l.Style.Equals(style, StringComparison.OrdinalIgnoreCase)
                                           && l.GroupId == (id == 0 ? null : new long?(groupId)))
                                 .OrderByDescending(l => l.LocalIid).ToList();
            var firstList = availableLists.FirstOrDefault();
            object selectedList = firstList == null ? null : firstList.Iid.ToString();
            var selectListRounds = new SelectList(availableLists, "Iid", "Round", selectedList);

            ViewBag.Rounds = selectListRounds;
            ViewBag.SelectedRound = selectedList;
            return PartialView();
        }

        public ActionResult GetList(long id, String divId)
        {
            ViewBag.DivID = divId;
            var header = db.Lists.Find(id);
            if (header == null)
                return new HttpNotFoundResult();
            ViewBag.Header = header;
            switch (header.ListType)
            {
                case ListTypeEnum.BoulderGroups:
                case ListTypeEnum.LeadGroups:
                    return RenderResultListSeveralRoutes(header);
                case ListTypeEnum.BoulderSimple:
                    return RenderSimpleResultList(header, h => h.ResultsBoulder, "RenderResultListBoulder");
                case ListTypeEnum.BoulderSuper:
                case ListTypeEnum.LeadSimple:
                    return RenderSimpleResultList(header, h => h.ResultsLead, "RenderResultListLead");
                case ListTypeEnum.LeadFlash:
                    return RenderResultListFlash(header);
                case ListTypeEnum.SpeedFinal:
                case ListTypeEnum.SpeedQualy:
                case ListTypeEnum.SpeedQualy2:
                    return RenderSimpleResultList(header, h => h.ResultsSpeed, "RenderResultListSpeed");
                default:
                    return new HttpNotFoundResult("Какой-то странный протокол");
            }
        }

        private ActionResult RenderResultListSeveralRoutes(ListHeaderModel header)
        {
            return new HttpNotFoundResult();
        }

        private static int ResultSorter(ListLineModel a, ListLineModel b)
        {
            if (a == null && b == null)
                return 0;
            if (a == null)
                return 1;
            if (b == null)
                return -1;
            int n = (a.Position ?? int.MaxValue).CompareTo(b.Position ?? int.MaxValue);
            if (n != 0)
                return n;
            return a.StartNumber.CompareTo(b.StartNumber);
        }

        private ActionResult RenderSimpleResultList<T>(ListHeaderModel header, Func<ListHeaderModel, IEnumerable<T>> selector, String viewName)
            where T : ListLineModel
        {
            var model = selector(header).ToList();
            model.Sort(ResultSorter);
            return PartialView(viewName, model);
        }

        private ActionResult RenderResultListGeneral(ListHeaderModel header)
        {
            return new HttpNotFoundResult();
        }


        private ActionResult RenderResultListFlash(ListHeaderModel header)
        {
            var results = ResultsController.GetFlashResult(header);
            var dataTable = SortingClass.CreateStructure();
            dataTable.Columns.Add("pos0", typeof(int));
            //dt.Rows.Add(res.Climber.Vk, 0, String.Empty, res.Climber.SecretaryId.Value, String.Empty,
            //                0.0, String.Empty, sp, curPos);
            //climbersWithResult.Add(res.Climber.SecretaryId.Value);
            foreach (var r in results.Values.OfType<ResultsController.FlashRoundResult>().Where(r=>r.RouteNum==1))
            {
                var climber = header.Competition.Climbers.FirstOrDefault(c => c.SecretaryId == r.ClimberId);
                if (climber == null)
                    continue;
                int sp;
                bool allDSQ = true, allDNS = true;
                foreach (var route in r.Routes)
                {
                    if (allDNS && !route.ResText.ToLowerInvariant().Contains("н/я"))
                        allDNS = false;
                    if (allDSQ && !route.ResText.ToLowerInvariant().Contains("дискв"))
                        allDSQ = false;
                    if (!allDNS || allDSQ)
                        break;
                }
                if (allDNS && allDSQ)

Web/_unused/WebClimbing/Views/Home/Calendar.cshtml
@model IEnumerable<CompetitionModel>
@{
    ClimbingContext db = ViewBag.Db;       
}
<div id="@ViewBag.DivID">
    @if (User.IsInRole(db, RoleEnum.Admin, (long?)ViewBag.Region))
    {
    <p>
        @Html.ActionLink("Новые соревнования", "Create", new { comp_year = ViewBag.Year, comp_region = ViewBag.Region })
    </p>
    }
    <table>
        <tr>
            <th></th>
            <th>@Html.DisplayNameFor(model=>model.Start)</th>
            <th>@Html.DisplayNameFor(model=>model.End)</th>
            <th>@Html.DisplayNameFor(model=>model.RegionId)</th>
            <th>@Html.DisplayNameFor(model=>model.Lead)</th>
            <th>@Html.DisplayNameFor(model=>model.Speed)</th>
            <th>@Html.DisplayNameFor(model=>model.Boulder)</th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @if (item.Lists.Count > 0)
                    {
                        @Html.ActionLink(String.Format("Результаты: {0}", item.Name), "Index", "Data", new { id = item.Iid }, null)
                    }
                    else
                    {
                        @Html.DisplayFor(model => item.Name)
                    }
                </td>
                <td>@item.Start.ToString("dd.MM.yyyy")</td>
                <td>@item.End.ToString("dd.MM.yyyy")</td>
                <td>@Html.DisplayFor(model=>item.Region.Name)</td>
                <td>@Html.DisplayFor(model=>item.Lead)</td>
                <td>@Html.DisplayFor(model=>item.Speed)</td>
                <td>@Html.DisplayFor(model=>item.Boulder)</td>
                <td>
                    @if (item.Climbers.Count > 0)
                    {
                        @Html.ActionLink("Список участников", "Climbers", new { id = item.Iid })
                    }
                    @if (item.AllowedToEdit(User.GetDbUser(db, false)))
                    {@*
                        @:| @Html.ActionLink("Подать заявку", "Index", "Applications", new { id = item.Iid }, null)
                     *@
                       
                        @:| @Html.ActionLink("Подать заявку", "Index", "Registration", new { id = item.Iid }, null)
                       
                    }
                    @if (User.IsInRoleComp(db, RoleEnum.Admin, item.Iid))
                    {
                        @:| @Html.ActionLink("Пользователи", "Roles", new { id = item.Iid })
                    }
                    @if (User.IsInRole(db, RoleEnum.Admin, item.Region.IidParent))
                    {
                        @:| @Html.ActionLink("Правка", "Edit", new { id = item.Iid })
                        @:| @Html.ActionLink("Удалить", "Delete", new { id = item.Iid })
                    }
                </td>
            </tr>
        }
    </table>
</div>